var map = { "height":10,
 "layers":[
        {
         "data":[3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 7, 8, 8, 8, 8, 8, 5, 4, 4, 3, 9, 4, 3, 3, 3, 3, 9, 4, 4, 4, 9, 3, 3, 4, 4, 3, 9, 3, 3, 4, 9, 3, 4, 4, 4, 3, 9, 3, 3, 4, 9, 3, 4, 3, 4, 3, 11, 8, 5, 4, 9, 4, 3, 3, 3, 4, 3, 3, 9, 3, 11, 8, 8, 8, 8, 8, 8, 8, 10, 3, 3, 4, 3, 3, 4, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 4],
         "height":10,
         "name":"Ground",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "height":10,
         "name":"Buildings",
         "objects":[
                {
                 "gid":1,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "width":0,
                 "x":318,
                 "y":550
                }, 
                {
                 "gid":2,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "width":0,
                 "x":312,
                 "y":434
                }, 
                {
                 "gid":12,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "width":0,
                 "x":265,
                 "y":279
                }, 
                {
                 "gid":12,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "width":0,
                 "x":140,
                 "y":186
                }, 
                {
                 "gid":14,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "width":0,
                 "x":180,
                 "y":428
                }, 
                {
                 "gid":14,
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "width":0,
                 "x":386,
                 "y":355
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }],
 "orientation":"isometric",
 "properties":
    {

    },
 "tileheight":62,
 "tilesets":[
        {
         "firstgid":1,
         "image":"..\/img\/arch-left.png",
         "imageheight":183,
         "imagewidth":151,
         "margin":0,
         "name":"arch-left",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":183,
         "tilewidth":151
        }, 
        {
         "firstgid":2,
         "image":"..\/img\/arch-right.png",
         "imageheight":130,
         "imagewidth":142,
         "margin":0,
         "name":"arch-right",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":130,
         "tilewidth":142
        }, 
        {
         "firstgid":3,
         "image":"..\/img\/terrain.png",
         "imageheight":204,
         "imagewidth":384,
         "margin":0,
         "name":"Ground",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":68,
         "tilewidth":128
        }, 
        {
         "firstgid":12,
         "image":"..\/img\/house-1.png",
         "imageheight":106,
         "imagewidth":129,
         "margin":0,
         "name":"house-1",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":106,
         "tilewidth":129
        }, 
        {
         "firstgid":13,
         "image":"..\/img\/house-1.png",
         "imageheight":106,
         "imagewidth":129,
         "margin":0,
         "name":"house-1",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":106,
         "tilewidth":129
        }, 
        {
         "firstgid":14,
         "image":"..\/img\/house-2.png",
         "imageheight":159,
         "imagewidth":129,
         "margin":0,
         "name":"house-2",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":159,
         "tilewidth":129
        }],
 "tilewidth":124,
 "version":1,
 "width":10
}